scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: speckle_filter
      type: laser_filters/LaserScanSpeckleFilter
      params:
        filter_type: 1
        max_range: 70.0
        max_range_difference: 0.3
        filter_window: 2
