sudo systemctl start ros2_susumu_robo_bringup
sudo systemctl start ros2_foxglove_bridge
sudo systemctl start ros2_msg_mid360
sudo systemctl start ros2_livox_to_pointcloud2
sudo systemctl start ros2_pointcloud_to_laserscan
sudo systemctl start ros2_diffdrive_ddsm115
sudo systemctl start ros2_odom_relay
sudo systemctl start ros2_tf_livox_frame
