sudo systemctl stop ros2_collision_monitor
sudo systemctl stop ros2_foxglove_bridge
# sudo systemctl stop ros2_kobuki_velocity_smoother
sudo systemctl stop ros2_micro_ros_agent
sudo systemctl stop ros2_teleop_twist_joy
sudo systemctl stop ros2_msg_mid360
sudo systemctl stop ros2_livox_to_pointcloud2
sudo systemctl stop ros2_pointcloud_to_laserscan
sudo systemctl stop ros2_twist_stamper
