ros2 run robot_upstart uninstall ros2_susumu_robo_bringup
ros2 run robot_upstart uninstall ros2_foxglove_bridge
ros2 run robot_upstart uninstall ros2_msg_mid360
ros2 run robot_upstart uninstall ros2_livox_to_pointcloud2
ros2 run robot_upstart uninstall ros2_pointcloud_to_laserscan
