ros2 run robot_upstart uninstall ros2_foxglove_bridge
ros2 run robot_upstart uninstall ros2_teleop_twist_joy
ros2 run robot_upstart uninstall ros2_collision_monitor
ros2 run robot_upstart uninstall ros2_kobuki_velocity_smoother
ros2 run robot_upstart uninstall ros2_micro_ros_agent
ros2 run robot_upstart uninstall ros2_msg_mid360
ros2 run robot_upstart uninstall ros2_livox_to_pointcloud2
